## PyTorch and tensors

- A tensor is a generalization of vectors and matrices to more dimensions.
- 0D tensor = scalar (single number)
- 1D tensor = vector
- 2D tensor = matrix
- 3D+ tensor = higher-dimensional arrays.

![](https://github.com/MrDredD/DL-bioinform/blob/main/week01/misc/meme.png?raw=1)

In [3]:
import torch
print(torch.__version__)
print("CUDA available:", torch.cuda.is_available())

2.2.0+cpu
CUDA available: False


In [13]:
# Scalar (0D)
s = torch.tensor(5)
print("Scalar:", s, "Shape:", s.shape)

Scalar: tensor(5) Shape: torch.Size([])


In [ ]:
# Vector (1D)
v = torch.tensor([1, 2, 3])
print("Vector:", v, "Shape:", v.shape)

In [17]:
# Matrix (2D)
M = torch.tensor([[1, 2], [3, 4]])
print("Matrix:", M, "Shape:", M.shape)

Matrix: tensor([[1, 2],
        [3, 4]]) Shape: torch.Size([2, 2])


In [19]:
# 3D Tensor
T = torch.rand(2, 3, 4)  # dimensions: 2 x 3 x 4
print("3D Tensor shape:", T.shape)

3D Tensor shape: torch.Size([2, 3, 4])


## Vectors (1D Tensors)

### Creating vectors

In [24]:
# From list
v1 = torch.tensor([1, 2, 3, 4])
print("v1:", v1)

v1: tensor([1, 2, 3, 4])


In [25]:
# Zeros vector
v2 = torch.zeros(5)
print("Zeros:", v2)

Zeros: tensor([0., 0., 0., 0., 0.])


In [26]:
# Ones vector
v3 = torch.ones(5)
print("Ones:", v3)

Ones: tensor([1., 1., 1., 1., 1.])


In [27]:
# Random vector
v4 = torch.rand(5)
print("Random:", v4)

Random: tensor([0.9690, 0.1839, 0.3725, 0.2810, 0.8019])


In [28]:
# Range (like Python range)
v5 = torch.arange(0, 10, 2)  # start, stop, step
print("Range:", v5)

Range: tensor([0, 2, 4, 6, 8])


In [29]:
# Linearly spaced values
v6 = torch.linspace(0, 1, steps=5)
print("Linspace:", v6)

Linspace: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


### Vector properties

In [30]:
v = torch.tensor([1., 2., 3., 4.])

In [31]:
print("Shape:", v.shape)
print("Dim:", v.dim())
print("Size:", v.size())
print("Data type:", v.dtype)

Shape: torch.Size([4])
Dim: 1
Size: torch.Size([4])
Data type: torch.float32


In [32]:
vi = torch.tensor([1, 2, 3], dtype=torch.int32)
print("Integer vector:", vi, vi.dtype)

Integer vector: tensor([1, 2, 3], dtype=torch.int32) torch.int32


### Indexing & Slicing

In [33]:
v = torch.tensor([10, 20, 30, 40, 50])

print("First element:", v[0])
print("Last element:", v[-1])
print("Slice 1:3:", v[1:3])    # elements at index 1 and 2
print("Every other element:", v[::2])

First element: tensor(10)
Last element: tensor(50)
Slice 1:3: tensor([20, 30])
Every other element: tensor([10, 30, 50])


### Vector operations

In [34]:
u = torch.tensor([1., 2., 3.])
v = torch.tensor([4., 5., 6.])

# Addition & subtraction
print("u + v =", u + v)
print("u - v =", u - v)

# Elementwise multiplication
print("u * v =", u * v)

# Scalar multiplication
print("2 * u =", 2 * u)

# Dot product
print("Dot product:", torch.dot(u, v))

# Norm (magnitude of vector)
print("Norm of u:", torch.norm(u))

u + v = tensor([5., 7., 9.])
u - v = tensor([-3., -3., -3.])
u * v = tensor([ 4., 10., 18.])
2 * u = tensor([2., 4., 6.])
Dot product: tensor(32.)
Norm of u: tensor(3.7417)


### Reshaping vectors --> matrices

In [35]:
v = torch.arange(1, 7)

In [36]:
M = v.reshape(2, 3)

In [37]:
v

tensor([1, 2, 3, 4, 5, 6])

In [38]:
M

tensor([[1, 2, 3],
        [4, 5, 6]])

### More vectors

In [99]:
v = torch.Tensor(range(1, 5))
v

tensor([1., 2., 3., 4.])

In [100]:
# Print number of dimensions (1D) and size of tensor
print(f'dim: {v.dim()}, size: {v.size()[0]}')

dim: 1, size: 4


In [101]:
v.numel()

4

In [102]:
w = torch.Tensor([1, 0, 2, 0])
w

tensor([1., 0., 2., 0.])

In [103]:
# Element-wise multiplication
v * w

tensor([1., 0., 6., 0.])

In [104]:
(v * w).sum()

tensor(7.)

In [105]:
# Scalar product: 1*1 + 2*0 + 3*2 + 4*0
v @ w

tensor(7.)

In [106]:
# In-place replacement of random number from 0 to 10
x = torch.Tensor(5).random_(10)
x

tensor([9., 6., 9., 5., 4.])

In [107]:
print(f'first: {x[0]}, last: {x[-1]}')

first: 9.0, last: 4.0


In [108]:
# Extract sub-Tensor [from:to)
x[1:2 + 1]

tensor([6., 9.])

In [109]:
v

tensor([1., 2., 3., 4.])

In [110]:
v.pow_(2)

tensor([ 1.,  4.,  9., 16.])

In [111]:
v

tensor([ 1.,  4.,  9., 16.])

In [112]:
# Square all elements in the tensor
print(v.pow(2), v)

tensor([  1.,  16.,  81., 256.]) tensor([ 1.,  4.,  9., 16.])


## Higher-dimensional tensors

In [49]:
# Generate a tensor of size 2x3x4

t = torch.Tensor(2, 3, 4) # creates an uninitialized tensor

In [50]:
type(t)

torch.Tensor

In [51]:
t

tensor([[[-2.4779e+27,  1.7684e-42,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [53]:
# Get the size of the tensor

tuple(t.size())

(2, 3, 4)

In [55]:
# Tensor slicing

t[:, :, 1]

tensor([[1.7684e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [56]:
# t.size() is a classic tuple =>
print('t size:', ' \u00D7 '.join(map(str, t.size())))

t size: 2 × 3 × 4


In [57]:
t.dim()

3

In [59]:
len(t)

2

In [60]:
# prints dimensional space and sub-dimensions
print(f'point in a {t.numel()} dimensional space')
print(f'organised in {t.dim()} sub-dimensions')

point in a 24 dimensional space
organised in 3 sub-dimensions


In [61]:
t = torch.Tensor(2, 3, 4)
t

tensor([[[-2.5154e+27,  1.7684e-42,  0.0000e+00,  2.4375e+00],
         [ 0.0000e+00,  2.5312e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [62]:
generator = torch.random.manual_seed(42)
generator

In [63]:
t.random_(10, 20, generator=generator)

tensor([[[12., 17., 16., 14.],
         [16., 15., 10., 14.],
         [10., 13., 18., 14.]],

        [[10., 14., 11., 12.],
         [15., 15., 17., 16.],
         [19., 16., 13., 11.]]])

In [64]:
t

tensor([[[12., 17., 16., 14.],
         [16., 15., 10., 14.],
         [10., 13., 18., 14.]],

        [[10., 14., 11., 12.],
         [15., 15., 17., 16.],
         [19., 16., 13., 11.]]])

In [65]:
# Mind the underscore!
# Any operation that mutates a tensor in-place is post-fixed with an _.
# For example: x.copy_(y), x.t_(), x.random_(n) will change x.
t = torch.Tensor(2, 3, 4)

t.random_(10)

tensor([[[9., 3., 1., 9.],
         [7., 9., 2., 0.],
         [5., 9., 3., 4.]],

        [[9., 6., 2., 0.],
         [6., 2., 7., 9.],
         [7., 3., 3., 4.]]])

In [66]:
t.size()

torch.Size([2, 3, 4])

In [67]:
# This resizes the tensor permanently
r = torch.Tensor(t)
r.resize_(3, 8)
r

tensor([[9., 3., 1., 9., 7., 9., 2., 0.],
        [5., 9., 3., 4., 9., 6., 2., 0.],
        [6., 2., 7., 9., 7., 3., 3., 4.]])

In [68]:
# As you can see zero_ would replace r with 0's which was originally filled with integers
r.zero_()

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
t

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [70]:
torch.zeros(3, 8)

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [71]:
s = r.clone()

In [72]:
s

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [73]:
# In-place fill of 1's
s.fill_(1)
s

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [74]:
r

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

## Matrices (2D Tensors)

In [114]:
m = torch.Tensor([[2, 5, 3, 7], [4, 2, 1, 9]])

In [115]:
m

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [116]:
import numpy as np

m = torch.Tensor(np.array([[2, 5, 3, 7], [4, 2, 1, 9]]))

In [117]:
m

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [118]:
type(m)

torch.Tensor

In [119]:
m.dim()

2

In [120]:
print(m.size(0), m.size(1), m.size(), sep=' -- ')

2 -- 4 -- torch.Size([2, 4])


In [121]:
# Returns the total number of elements, hence num-el (number of elements)
m.numel()

8

In [122]:
# Indexing row 0, column 2 (0-indexed)
m[0][2]

tensor(3.)

In [123]:
# Indexing row 0, column 2 (0-indexed)
m[0, 2]

tensor(3.)

In [124]:
# Indexing column 1, all rows (returns size 2)
m[:, 1]

tensor([5., 2.])

In [125]:
# Indexing column 1, all rows (returns size 2x1)
m[:, [1, 2] * 2]

tensor([[5., 3., 5., 3.],
        [2., 1., 2., 1.]])

In [126]:
# Indexes row 0, all columns (returns 1x4)
m[[0, 1] * 3, :]

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.],
        [2., 5., 3., 7.],
        [4., 2., 1., 9.],
        [2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [127]:
# Indexes row 0, all columns (returns size 4)
m[0, :]

tensor([2., 5., 3., 7.])

In [128]:
# Create tensor of numbers from 1 to 5 (excluding 5)
v = torch.arange(1., 4 + 1)
v

tensor([1., 2., 3., 4.])

In [129]:
m

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [130]:
# Scalar product
m @ v

tensor([49., 47.])

In [131]:
# Calculated by 1*2 + 2*5 + 3*3 + 4*7
m[[0], :] @ v

tensor([49.])

In [132]:
# Calculated by
m[[1], :] @ v

tensor([47.])

In [133]:
# Add a random tensor of size 2x4 to m
m + torch.rand(2, 4)

tensor([[2.8913, 5.1447, 3.5315, 7.1587],
        [4.6542, 2.3278, 1.6532, 9.3958]])

In [134]:
# Subtract a random tensor of size 2x4 to m
m - torch.rand(2, 4)

tensor([[1.0853, 4.7964, 2.7982, 6.7982],
        [3.0503, 1.3334, 0.0189, 8.9126]])

In [135]:
# Multiply a random tensor of size 2x4 to m
m * torch.rand(2, 4)

tensor([[0.0081, 0.5441, 0.4910, 4.9176],
        [2.7162, 1.8309, 0.2418, 1.4323]])

In [136]:
# Divide m by a random tensor of size 2x4
m / torch.rand(2, 4)

tensor([[ 2.6134, 16.7843,  3.7338, 18.3559],
        [ 5.0889, 17.9346,  4.0375, 13.7944]])

In [137]:
m.size()

torch.Size([2, 4])

In [138]:
# Transpose tensor m, which is essentially 2x4 to 4x2
m.t()

tensor([[2., 4.],
        [5., 2.],
        [3., 1.],
        [7., 9.]])

In [139]:
# Same as
m.transpose(0, 1)

tensor([[2., 4.],
        [5., 2.],
        [3., 1.],
        [7., 9.]])

In [140]:
torch.rand(2, 4, 5).transpose(2, 0).size()

torch.Size([5, 4, 2])

## Constructors

In [141]:
torch.arange(3., 8 + 1, dtype=torch.float32)

tensor([3., 4., 5., 6., 7., 8.])

In [142]:
# Create tensor from 5.7 to -2.1 with each having a space of -3
torch.arange(5.7, -2.1, -3)

tensor([ 5.7000,  2.7000, -0.3000])

In [143]:
# returns a 1D tensor of steps equally spaced points between start=3, end=8 and steps=20
torch.linspace(3, 8, 20).view(1, -1)

tensor([[3.0000, 3.2632, 3.5263, 3.7895, 4.0526, 4.3158, 4.5789, 4.8421, 5.1053,
         5.3684, 5.6316, 5.8947, 6.1579, 6.4211, 6.6842, 6.9474, 7.2105, 7.4737,
         7.7368, 8.0000]])

In [144]:
v = torch.randint(0, 10, (2, 4))

In [145]:
v

tensor([[7, 8, 6, 0],
        [6, 8, 6, 8]])

In [146]:
w = v.view(8, 1)

In [147]:
w

tensor([[7],
        [8],
        [6],
        [0],
        [6],
        [8],
        [6],
        [8]])

In [148]:
# Create a tensor with the diagonal filled with 1
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## Casting

In [149]:
torch.*Tensor?

torch.BFloat16Tensor
torch.BoolTensor
torch.ByteTensor
torch.CharTensor
torch.DoubleTensor
torch.FloatTensor
torch.HalfTensor
torch.IntTensor
torch.LongTensor
torch.ShortTensor
torch.Tensor

In [150]:
m

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [151]:
m_double = m.double()
m_double

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]], dtype=torch.float64)

In [152]:
m_byte = m.byte()
m_byte

tensor([[2, 5, 3, 7],
        [4, 2, 1, 9]], dtype=torch.uint8)

In [153]:
torch.cuda.is_available()

False

In [154]:
# Move your tensor to GPU device 0 if there is one (first GPU in the system)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
m.to(device)

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [155]:
md = m.to(device)
md

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [156]:
md.cpu().numpy()

array([[2., 5., 3., 7.],
       [4., 2., 1., 9.]], dtype=float32)

In [157]:
m.to(device) * md

tensor([[ 4., 25.,  9., 49.],
        [16.,  4.,  1., 81.]])

In [158]:
# Converts tensor to numpy array
m_np = m.numpy()
m_np

array([[2., 5., 3., 7.],
       [4., 2., 1., 9.]], dtype=float32)

In [159]:
# In-place fill of column 0 and row 0 with value -1
m_np[0, 0] = -1
m_np

array([[-1.,  5.,  3.,  7.],
       [ 4.,  2.,  1.,  9.]], dtype=float32)

In [160]:
m

tensor([[-1.,  5.,  3.,  7.],
        [ 4.,  2.,  1.,  9.]])

In [161]:
# Create a tensor of integers ranging from 0 to 4
import numpy as np
n_np = np.arange(5)
n = torch.from_numpy(n_np)
print(n_np, n)

[0 1 2 3 4] tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [162]:
# In-place multiplication of all elements by 2 for tensor n
# Because n is essentially n_np, not a clone, this affects n_np
n.mul_(2)
n_np

array([0, 2, 4, 6, 8])

## More fun

In [163]:
# Creates two tensors of size 1x4
a = torch.Tensor([[1, 2, 3, 4]])
b = torch.Tensor([[5, 6, 7, 8]])
print(a.size(), b)

torch.Size([1, 4]) tensor([[5., 6., 7., 8.]])


In [164]:
# Concatenate on axis 0, so you get 2x4
torch.cat((a, b), 0)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [165]:
# Concatenate on axis 1, so you get 1x8
torch.cat((a, b), 1)

tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])