In [1]:
import numpy as np

A = np.array([
    [1, 3, 4],
    [3, 3, 1],
    [4, 1, 2]
])

# Находим собственные значения и собственные векторы
eigvals, eigvecs = np.linalg.eigh(A)

print("Собственные значения:")
print(eigvals)

print("\nМатрица собственных векторов (столбцы — нормированные собственные векторы):")
print(eigvecs)

# Проверка разложения A = V Λ V^T
Lambda = np.diag(eigvals)
A_reconstructed = eigvecs @ Lambda @ eigvecs.T

print("\nПроверка: восстановленная матрица A:")
print(A_reconstructed)

Собственные значения:
[-3.02069926  1.66527771  7.35542155]

Матрица собственных векторов (столбцы — нормированные собственные векторы):
[[ 0.77532334  0.1440438  -0.61491877]
 [-0.2934401  -0.78000906 -0.55270134]
 [-0.55925542  0.60896408 -0.562491  ]]

Проверка: восстановленная матрица A:
[[1. 3. 4.]
 [3. 3. 1.]
 [4. 1. 2.]]
