## 🧠 **NumPy Exam — 10 Coding Questions**

⚡ **JUNIOR ML ENGINEER LEVEL**


> **Instructions:**
> Use only NumPy (no pure Python loops unless specified).
> You can import as:
>
> ```python
> import numpy as np
> ```

---

### **1️⃣ Create an array**

Create a 2D NumPy array with **3 rows** and **4 columns**, filled with **random floats between 10 and 20**.

---

### **2️⃣ Array properties**

Given:

```python
a = np.array([[1, 2, 3], [4, 5, 6]])
```

Write code to print:

* The number of dimensions
* The shape
* The data type

---

### **3️⃣ Reshaping**

Using:

```python
a = np.arange(12)
```

Reshape `a` into a 3×4 matrix.

---

### **4️⃣ Indexing and slicing**

Given:

```python
a = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
              [90, 100, 110, 120]])
```

Extract:

* The **second row**
* The **first column**
* The **sub-matrix** containing the middle 2×2 block (`[[60,70],[100,110]]`)

---

### **5️⃣ Conditional selection**

Given:

```python
a = np.array([12, 5, 8, 22, 17, 3, 10])
```

Select all elements **greater than 10**, and return them as a new array.

---

### **6️⃣ Broadcasting**

Create:

```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])
```

Add `b` to `a` using broadcasting (no loops).

---

### **7️⃣ Axis operations**

Given:

```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])
```

Compute:

* The sum of all elements
* The mean **along axis=0**
* The max **along axis=1**

---

### **8️⃣ Boolean masking**

Given:

```python
a = np.array([5, 10, 15, 20, 25, 30])
```

Replace all elements **greater than 15** with **0**.

---

### **9️⃣ Linear algebra**

Create a 2×2 matrix:

```python
A = np.array([[2, 1],
              [5, 3]])
```

Find:

* The determinant
* The inverse
* Verify that `A @ A_inv` is (approximately) the identity matrix.

---

### **🔟 Combine & flatten**

Given:

```python
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
```

1. Stack them vertically into one array
2. Flatten the result into a 1D array

---

### 💯 **Bonus (optional):**

Without using loops, create a 5×5 identity matrix and set the **main diagonal** to 7 instead of 1.

---


## Solutions

In [1]:
import numpy as np

### 1. ✅

Create a 2D NumPy array with **3 rows** and **4 columns**, filled with **random floats between 10 and 20**.

In [17]:
arr = np.random.uniform(low=10.0, high=20.0, size=(3,4))

In [18]:
arr

array([[13.15677539, 14.56598204, 18.47711086, 11.83829081],
       [17.06426613, 19.04436331, 13.67756155, 16.04996673],
       [18.6129718 , 19.05755631, 11.82713703, 16.75445731]])

### 2. ✅

Given:

```python
a = np.array([[1, 2, 3], [4, 5, 6]])
```

Write code to print:

* The number of dimensions
* The shape
* The data type

In [22]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.ndim)
print(a.shape)
print(a.dtype)

2
(2, 3)
int32


### 3. ✅

Using:

```python
a = np.arange(12)
```

Reshape `a` into a 3×4 matrix.

In [25]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 4. ✅

Given:

```python
a = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
              [90, 100, 110, 120]])
```

Extract:

* The **second row**
* The **first column**
* The **sub-matrix** containing the middle 2×2 block (`[[60,70],[100,110]]`)

In [31]:
a = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
              [90, 100, 110, 120]])

print(a[1])
print(a[:, 0])
print(a[1:, 1:3])

[50 60 70 80]
[10 50 90]
[[ 60  70]
 [100 110]]


### 5. ✅

Given:

```python
a = np.array([12, 5, 8, 22, 17, 3, 10])
```

Select all elements **greater than 10**, and return them as a new array.

In [32]:
a = np.array([12, 5, 8, 22, 17, 3, 10])

b = a[a > 10]

In [33]:
b

array([12, 22, 17])

### 6. ✅

Create:

```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])
```

Add `b` to `a` using broadcasting (no loops).

In [34]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

c =  np.add(a, b)

print(c)

[[11 22 33]
 [14 25 36]]


### 7. ✅

Given:

```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])
```

Compute:

* The sum of all elements
* The mean **along axis=0**
* The max **along axis=1**

In [36]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.sum())
print(a.mean(axis=0))
print(a.max(axis=1))

21
[2.5 3.5 4.5]
[3 6]


### 8. ✅ 

Given:

```python
a = np.array([5, 10, 15, 20, 25, 30])
```

Replace all elements **greater than 15** with **0**.

In [37]:
a = np.array([5, 10, 15, 20, 25, 30])

a[a > 15] = 0

print(a)

[ 5 10 15  0  0  0]


### 9. ✅

Create a 2×2 matrix:

```python
A = np.array([[2, 1],
              [5, 3]])
```

Find:

* The determinant
* The inverse
* Verify that `A @ A_inv` is (approximately) the identity matrix.

In [41]:
A = np.array([[2, 1],
              [5, 3]])

print("det(A) = ", (A[0, 0] * A[1, 1]) - (A[0, 1] * A[1, 0]))
print("det(A) = ", np.linalg.det(A))

det(A) =  1
det(A) =  1.0000000000000009


In [43]:
# 1) Determinant
detA = np.linalg.det(A)

# 2) Inverse
A_inv = np.linalg.inv(A)

# 3) Verify A @ A_inv ≈ I
I_approx = A @ A_inv
is_identity = np.allclose(I_approx, np.eye(2))  # tolerates tiny float errors

print("A =\n", A)
print("det(A) =", detA)
print("A_inv =\n", A_inv)
print("A @ A_inv =\n", I_approx)
print("Is identity (within tolerance)?", is_identity)

A =
 [[2 1]
 [5 3]]
det(A) = 1.0000000000000009
A_inv =
 [[ 3. -1.]
 [-5.  2.]]
A @ A_inv =
 [[ 1.00000000e+00  2.22044605e-16]
 [-8.88178420e-16  1.00000000e+00]]
Is identity (within tolerance)? True


### 10. ✅ 

Given:

```python
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
```

1. Stack them vertically into one array
2. Flatten the result into a 1D array

In [48]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

c = np.vstack((a, b))
print(c)

d = c.flatten()
print(d)


[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


### Bonus.

Without using loops, create a 5×5 identity matrix and set the **main diagonal** to 7 instead of 1.

In [49]:
# Create a 5x5 identity matrix
I = np.eye(5)

# Multiply the main diagonal by 7
I *= 7

print(I)

[[7. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0.]
 [0. 0. 7. 0. 0.]
 [0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 7.]]
