# NumPy Tutorial

NumPy = **Num**erical **Py**thon

"NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more."

https://numpy.org/

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [3]:
a.shape

(2, 3)

"NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU."

## Array fundamentals

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])

In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a[0]

1

In [7]:
a[0] = 10

In [8]:
a

array([10,  2,  3,  4,  5,  6])

In [9]:
a[:3]

array([10,  2,  3])

- View: an object that refers to the data in the original array.

In [10]:
b = a[3:]
b

array([4, 5, 6])

- The original array can be mutated using the view.

In [11]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

- Copies and views: https://numpy.org/doc/stable/user/basics.copies.html#basics-copies-and-views

In [12]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
a[1][3]

8