# NumPy Tutorial

NumPy = **Num**erical **Py**thon

"NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more."

https://numpy.org/

In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [4]:
a.shape

(2, 3)

"NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU."

## Array fundamentals

In [5]:
a = np.array([1, 2, 3, 4, 5, 6])

In [6]:
a

array([1, 2, 3, 4, 5, 6])

In [7]:
a[0]

1

In [8]:
a[0] = 10

In [9]:
a

array([10,  2,  3,  4,  5,  6])

In [10]:
a[:3]

array([10,  2,  3])

- View: an object that refers to the data in the original array.

In [11]:
b = a[3:]
b

array([4, 5, 6])

- The original array can be mutated using the view.

In [12]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

- Copies and views: https://numpy.org/doc/stable/user/basics.copies.html#basics-copies-and-views

In [13]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
a[1][3]

8

## Array attributes

In [21]:
a = np.array([1, 2, 3])  # This is a simple 1D vector of length 3

- `ndim` = number of dimensions

In [22]:
a.ndim

1

In [23]:
a.shape

(3,)

In [24]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [25]:
a.ndim

2

- The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

In [26]:
a.shape

(3, 4)

- The fixed, total number of elements in array is contained in the `size` attribute.

In [27]:
a.size

12

In [28]:
import math

In [29]:
a.size == math.prod(a.shape)

True

- Arrays are typically "homogeneous", which means they contain elements of the same data type.
- The data type is recorded in the `dtype` attribute.

In [30]:
a.dtype

dtype('int32')

- For those who do not know:
    - `int32` means **32-bit integer** which is an integer (oh really??) that is stored using 32 binary digits (bits) → each can be either 0 or 1.
    - 32 bits = sequence of 32 zeros or ones.
    - For example, `00000000 00000000 00000000 00000001` → represents the number 1

## How to create a basic array

In [32]:
np.zeros(2)

array([0., 0.])

In [33]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [34]:
np.empty(2)

array([0., 0.])

In [35]:
np.arange(4)

array([0, 1, 2, 3])

In [36]:
np.arange(2, 13, 2)

array([ 2,  4,  6,  8, 10, 12])

In [37]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [38]:
np.linspace(0, 10, num=6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [39]:
np.linspace(0, 10, num=7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [40]:
x = np.ones(2, dtype=np.int64)

In [41]:
x

array([1, 1], dtype=int64)

## Adding, removing, and sorting elements

In [42]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [43]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [45]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [49]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## How do you know the shape and size of an array?

In [50]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [51]:
array_example.ndim

3

In [52]:
array_example.size

24

In [53]:
array_example.shape

(3, 2, 4)

## Can you reshape an array?

In [55]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
b = a.reshape(a, 3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [68]:
np.reshape(a, (1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

## Convert a 1D array into a 2D array

In [69]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [72]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [73]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [74]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [75]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [76]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [77]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

## Indexing and Slicing

In [78]:
data = np.array([1, 2, 3])
data[1]

2

In [79]:
data[0:2]

array([1, 2])

In [80]:
data[1:]

array([2, 3])

In [81]:
data[-2:]

array([2, 3])

In [82]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [83]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [84]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [85]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [86]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [87]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [88]:
list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [89]:
print(a[b])

[1 2 3 4]


## How to create an array from existing data

In [90]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [92]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [93]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [94]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [95]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [96]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [97]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

- "Views are an important NumPy concept! NumPy functions, as well as operations like indexing and slicing, will return views whenever possible. This saves memory and is faster (no copy of the data has to be made). However it’s important to be aware of this - **modifying data in a view also modifies the original array**!"

In [98]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [99]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [100]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [101]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
b2 = a.copy()

In [103]:
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
b2[0] = 100

In [105]:
b2

array([[100, 100, 100, 100],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [106]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])